version: "3"
services:
  apollo-next-client:
    build: ./client
    image: apollo-next-client:latest
    container_name: apollo-next-client
    restart: always
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:80
  apollo-next-server:
    build: ./server
    image: apollo-next-server:latest
    container_name: apollo-next-server
    volumes:
      - ./server:/usr/src/app
    restart: always
    ports:
    - 5000:81